### ISSUE TITLE
Feature Request: Hide Files

### ISSUE THREAD

**Issue by lmangani** [QXIP/webshark-ui#1]
In order to operate in kios mode (public) we need to optionally hide the file browser and only leave the ability to upload.

- Ideally this should be controlled by a build-time parameter to produce a normal or kiosk release.
- In kiosk mode files should not be simply hidden. The list function should not be invoked at all.

**Comment by RFbkak37y3kIY** [comment]
added cli for kiosk mode

```
npm run build:kiosk
```

![image](https://github.com/QXIP/webshark-ui/assets/10195789/e83d0ee4-aeaa-47a6-8e69-6819d15cdc84)
